# Generated by Django 5.0.4 on 2024-04-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_paymentmethod_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='apartment_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='device_mac',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='device_serial_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='unit_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
