# Generated by Django 5.0.4 on 2024-04-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_contacts_apartment_name_contacts_device_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
