# Generated by Django 5.0.4 on 2024-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='stations', to='admin_app.users'),
        ),
    ]
