# Generated by Django 5.0.4 on 2024-04-17 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_permission_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='IP address or domain name', max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.station')),
            ],
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('end_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.router')),
            ],
        ),
    ]
